name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
projects: ["ISRO-web"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"
  - type: checkboxes
    id: issue-check
    attributes:
      label: Is there any existing issue for this?
      description: Please search to see if an issue already exist for the bug you encountered.
      options:
        - label: I have searched the existing issues.
          required: true        
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us details about the bug you encountered!
      placeholder: Tell a brief description of the bug!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: Add-Screenshots
    attributes:
      label: proof?
      description: Also share us the specific bug picture.
      placeholder: add sufficient SS to explain your issue.
      value: "A bug  screenshots!"
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: code-terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: checkboxes
    id: issue-terms
    attributes:
      label: I want to work on this issue
      description: I want to work on this issue
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true